### ISSUE TITLE
the execution count shows empty instead of "*" when executing

### ISSUE THREAD

**Issue by fcollonval** [datalayer/jupyter-server-nbmodel#13]
reported by @krassowski in https://github.com/jupyterlab/jupyter-collaboration/pull/307#issuecomment-2115634307

**Comment by abhijeetgurle-dream11** [comment]
Hey @fcollonval @krassowski is this issue resolved? 

I am trying to fix it on my local with all the mentioned versions of dependencies as mentioned [here](https://github.com/jupyterlab/jupyterlab/issues/16059#issuecomment-2288271750), but it is not getting fixed even installing all the correct versions of the libraries.

**Comment by abhijeetgurle-dream11** [comment]
Hey @fcollonval @krassowski anything I am missing as shared in above message?

**Comment by krassowski** [comment]
@abhijeetgurle-dream11 no good idea as to why it is not working for you. It would be easier to test if the changes from https://github.com/datalayer/jupyter-server-nbmodel/pull/25 were released.

**Comment by abhijeetgurle-dream11** [comment]
Hey @krassowski any idea when the changes will be released?

**Comment by abhijeetgurle-dream11** [comment]
Also, can you tell me if I am using the correct versions of the libraries as mentioned in the above thread?
