### ISSUE TITLE
Alpha release on PyPI?

### ISSUE THREAD

**Issue by krassowski** [datalayer/jupyter-server-nbmodel#19]
It would be good to publish to PyPI for two reasons:
- allow wider testing
- reserve the name against malicious use

Currently I see 404: https://pypi.org/project/jupyter-server-nbmodel/

**Comment by krassowski** [comment]
@echarles / @fcollonval any thoughts?

FYI the changes that were required on jupyter-collaboration side are available in beta0 (https://github.com/jupyterlab/jupyter-collaboration/issues/325#issuecomment-2232859023). Would it make sense to add these to dependencies?

**Comment by fcollonval** [comment]
> Would it make sense to add these to dependencies?

Definitely

**Comment by krassowski** [comment]
As for adding `jupyter-server-ydoc` and `jupyter-docprovider` as dependencies over the entire `jupyter-collaboration`, this is kind of blocked because of https://github.com/jupyterlab/jupyter-collaboration/issues/330.

**Comment by krassowski** [comment]
I opened https://github.com/datalayer/jupyter-server-nbmodel/pull/21

**Comment by fcollonval** [comment]
First alpha version released: https://pypi.org/project/jupyter-server-nbmodel/

**Comment by echarles** [comment]
Awesome @fcollonval  🎉
