### ISSUE TITLE
intermittently notebooks are taking long time to load after installing jupyter-server-nbmodel extensions.

### ISSUE THREAD

**Issue by abhijeetgurle-dream11** [datalayer/jupyter-server-nbmodel#28]
## Description

I have recently installed [jupyter-server-nbmodel](https://github.com/datalayer/jupyter-server-nbmodel) extension on my jupyterlab setup. After installing it, notebooks are taking long time to load even on my local. It took around 4.5min to load a simple notebook with 6KB data. I have observed that the issue happens with older notebooks and not the notebooks which are created after the extension is installed.

<img width="1724" alt="Screenshot 2024-11-19 at 5 23 54 PM" src="https://github.com/user-attachments/assets/5f53ceaa-9528-4413-ade3-999fe2d92692">

<img width="1728" alt="Screenshot 2024-11-19 at 5 39 18 PM" src="https://github.com/user-attachments/assets/66aa90fc-85cd-495f-b928-d2fedec4159c">

## Reproduce

1. Install [jupyter-server-nbmodel](https://github.com/datalayer/jupyter-server-nbmodel)
2. Open multiple notebooks and see how much time it takes to load the notebook

## Expected behavior

The notebook should open normally as it would open without the extension.

## Context

- Datalayer version: Jupyterlab 4.3.0
- Operating System and version: MacOS Sonoma
- Browser and version: 4.3.0

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by fcollonval** [comment]
Maybe related to https://github.com/jupyterlab/jupyter-collaboration/issues/398

**Comment by abhijeetgurle-dream11** [comment]
The root cause of the mentioned issue and my current issue can be same, but I resolved that issue by upgrading the jupyter version and I started getting the current issue.

**Comment by abhijeetgurle-dream11** [comment]
Hey @fcollonval, anything that we can do to resolve the issue? We want to use this extension in our prod setup and blocked becuase we are facing this issue.
