### ISSUE TITLE
Should code be executed asynchronously in RTC mode?

### ISSUE THREAD

**Issue by Wh1isper** [datalayer/jupyter-server-nbmodel#7]
### Problem

https://github.com/datalayer/jupyter-server-nbmodel/blob/b122d68e2c9608f24201aa757a47ea922147825d/jupyter_server_nbmodel/handlers.py#L125-L131

I've found that current implementations where cell takes longer to execute can lead to http request timeouts (especially behind some reverse proxies), and it's difficult for the front-end to determine if the request to execute the code was successfully sent.

### Proposed Solution

1. We can simply support asynchronous mode: do execute and safe in an asyncio.Task.
2. Maybe we need an optimistic lock to prevent racing  when concurrent write to the ynotebook.

**Comment by fcollonval** [comment]
Hey @Wh1isper thanks for testing, actually we cannot switch to asynchronous mode fully to be able to support the input case.

I plan to implement the following logic that will cover that case:

1. Return 202 with `Location` to get the execution result when receiving the request
2. On the result endpoint, return early if an input is needed otherwise return the results

**Comment by Wh1isper** [comment]
> Return 202 with Location to get the execution result when receiving the request

It sounds like we can only perform one code execution operation at a time? Or we will relay on kernel's zmq queue?

**Comment by fcollonval** [comment]
@Wh1isper I opened https://github.com/datalayer/jupyter-server-nbmodel/pull/9 which implements my proposal (it requires the latest version of https://github.com/jupyterlab/jupyter-collaboration/pull/307), if you want to have a look.

The solution I have in mind for stdin does not work. Currently the server is locked on an `input` request. If you have any idea to work around that. I'll be happy to hear them.
